### ISSUE TITLE
shape inconsistency in the 'cats_and_dogs' dataset

### ISSUE THREAD

**Issue by pedrovsglima** [fcoelhomrc/heuristics-fsmp#4]
error message:

RuntimeError: stack expects each tensor to be equal size, but got [3, 512, 512] at entry 0 and [1, 512, 512] at entry 17

![image](https://github.com/user-attachments/assets/4491baf1-a5fd-40ba-8843-2cd965e7529b)

**Comment by fcoelhomrc** [comment]
commit 2930a2715d314bf5fbcb98bad00c7b3bcc997ae8  fixes  this issue, please merge from `dev-finetuning`

**Comment by fcoelhomrc** [comment]
i still have some work to do on that branch before opening the PR
